spring:
  application:
    name: CONFIG-SERVER
      
eureka:
  intance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-erureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka
  
